kind = "mobile"
previewPath = "/"
title = "MemoirMuse"
version = "1.0.0"
id = "artifacts/memoirmuse"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/" ]
localPort = 22631

[services.development]
run = "pnpm --filter @workspace/memoirmuse run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/memoirmuse", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/memoirmuse", "run", "serve" ]

[services.env]
PORT = "22631"
BASE_PATH = "/"
